### ISSUE TITLE
兄弟,可以增加阿里云机器人推送

### ISSUE THREAD

**Issue by jarryyen** [imoki/sign_script#1]
RT

**Comment by imoki** [comment]
感谢建议，之后试试

**Comment by jarryyen** [comment]
> 

// 推送dingtalk bot
function dingtalkbot(message){
  let url = "https://oapi.dingtalk.com/robot/send?access_token=ooxx";
  let resp = HTTP.post(url, {"msgtype":"text","text":{"content":message}});
}


特别方便,加2行就完事了.我已经在用了,不过目前都是用的关键词机器人

**Comment by imoki** [comment]
抱歉，之前没弄成功所以一直没加入，我之后再试一下。非常感谢代码提供。

**Comment by imoki** [comment]
已增加钉钉机器人推送，感谢对项目的贡献
