### ISSUE TITLE
52破解和在线工具的cookie有两个每次都在变的值

### ISSUE THREAD

**Issue by peter0511** [imoki/sign_script#10]
Hm_lpvt_0fba23df1ee7ec49af558fb29456f532=
_access=
这两个值也在cookie里面     每次都失败这个怎么破呢
求大神帮助

**Comment by imoki** [comment]
这个不需要，不用管。吾爱cookie中只要有这两个键值对就可以了：htVC_2132_saltkey=xxxxxxxx; htVC_2132_auth=xxxxxxxx;

**Comment by imoki** [comment]
检查以下错误
1.是否有添加网络API，要添加
2.ck是否填写正确。
3.ck前后是否有多余的内容，如换行、双引号等。需要删掉

**Comment by peter0511** [comment]
> 这个不需要，不用管。吾爱cookie中只要有这两个键值对就可以了：htVC_2132_saltkey=xxxxxxxx; htVC_2132_auth=xxxxxxxx;

老师，我把其他的内容全部删了   就留了这两个值   还是不对

**Comment by imoki** [comment]
进群发下报错信息看看。“默库”公众号有群二维码。

**Comment by imoki** [comment]
复制DEBUG文件夹下的代码，运行看下报错信息提示什么
