### ISSUE TITLE
在线工具不能签到了  

### ISSUE THREAD

**Issue by chase1dream** [imoki/sign_script#19]
在线工具不能签到了

**Comment by imoki** [comment]
刚刚经过测试，还能签到
![image](https://github.com/imoki/sign_script/assets/78804251/228240bd-2c21-423f-99e9-53ea29280a84)

**Comment by imoki** [comment]
检查下是不是cookie过期了

**Comment by kangxiaohui** [comment]
![image](https://github.com/imoki/sign_script/assets/33645431/788639b5-7c6e-4ae4-bb4b-78a47bc3db92)
![image](https://github.com/imoki/sign_script/assets/33645431/be2518f1-54b2-49f6-8c0b-2324258ae7c8)
![image](https://github.com/imoki/sign_script/assets/33645431/f7259f36-e631-4a14-9bca-0007d4640b7a)
帮忙看一下，谢谢好心人

**Comment by imoki** [comment]
ck位置正确。你把ck发以文字形式发来，我这边测试下

**Comment by chase1dream** [comment]
uuid=a90142ef-4e79-451e-8e5a-19d8042cf137; _session=%7B%22slim.flash%22%3A%5B%5D%7D; _token=fEK0hW2WTOXebrg14tnu4OjI%2B32ZfTraDlFDXoBr8hHF8sAiIrRKfIA5c83%2B%2FDKl9GZhpXxWijg5Gnb8GnzrIvwIaVaUvhJHVLDG29GxxfI%3D; _access=796b603335d21b5bc977543695d31c7472ed169dbddb4070c307f4b4213ca02c









------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "imoki/sign_script"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月5日(星期天) 下午2:14
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [imoki/sign_script] 在线工具不能签到了   (Issue #19)





 
ck位置正确。你把ck发以文字形式发来，我这边测试下

**Comment by imoki** [comment]
应该是没登录，你的ck会重定向到登录页面。你访问https://id.tool.lu/login进行登录，重新抓取最新ck就行

**Comment by chase1dream** [comment]
已经登录了，还是显示失败

**Comment by imoki** [comment]
新的ck发来我看看

**Comment by chase1dream** [comment]
uuid=a90142ef-4e79-451e-8e5a-19d8042cf137; _session=%7B%22slim.flash%22%3A%5B%5D%7D; _token=WY4sqUYSx0o%2BCW5WwJf5NdluG5TKYj6jR9%2FJl9sP%2FEbDP%2BWOWcz80hrQLa7jGvV1ikL0Otf01M%2BYSwCa43YXHTM%2Fv2LH56C0R8UnWfdoyA0%3D; _access=796b603335d21b5bc977543695d31c74d51c25f55db894754be1d2f97b793089


要不算了，这个就这样吧，不迁到了，反正用得少，想起来我手动得了哈哈哈。另外，建议大佬增加一个看雪论坛的签到，想成为正式会员太难了，我这不太懂代码，看到一个github连接还能用，建议加入到这个表格中来

**Comment by imoki** [comment]
确实也依旧会重定向到登录

**Comment by imoki** [comment]
好的，看雪的我之后试试。之后若能做成功，会发到公众号上

**Comment by chase1dream** [comment]
好的，辛苦了

**Comment by imoki** [comment]
已增加【看雪论坛】脚本

**Comment by chase1dream** [comment]
好的  辛苦了大佬
