### ISSUE TITLE
bilbil

### ISSUE THREAD

**Issue by Su0515** [imoki/sign_script#28]
环境变量名称填什么啊没找到。

**Comment by imoki** [comment]
notion链接有教程。填表名，就是代码开头“【bilibili】” 里面的bilibili

**Comment by Su0515** [comment]
> notation链接有教程。填表名，就是代码开头'=“bilibili”;'里面的bilibili

我用的青龙 
![image](https://github.com/imoki/sign_script/assets/124444534/bd1b4c56-b5c9-4584-a69a-9a167190ea62)

**Comment by imoki** [comment]
环境变量名称就是填bilibili，然后值填cookie

**Comment by Su0515** [comment]
还是这个错误

**Comment by imoki** [comment]
好的我去检查下

**Comment by imoki** [comment]
![image](https://github.com/imoki/sign_script/assets/78804251/0b99d93c-4b91-41dc-81d7-b676741b798e)

**Comment by imoki** [comment]
![image](https://github.com/imoki/sign_script/assets/78804251/d2392af8-dbc2-412d-8fdc-3dd88c56086f)

**Comment by imoki** [comment]
> 还是这个错误

应该是你在配置文件config.sh中export bilibili=“xxxx”，刚刚测试不行。需要在“环境变量”栏目中配置。这类问题我下次看看能不能兼容
