### ISSUE TITLE
可以新增邮箱推送

### ISSUE THREAD

**Issue by darkbfly** [imoki/sign_script#3]
function email(message) {
    var myDate = new Date(); // 创建一个表示当前时间的 Date 对象
    var data_time = myDate.toLocaleDateString(); // 获取当前日期的字符串表示
    let zdy_username = Application.Range("J" + 2).Text
    let zdy_pasd = Application.Range("K" + 2).Text
    let zdy_host = Application.Range("L" + 2).Text
    let zdy_post = parseInt(Application.Range("M" + 2).Text)
    let push = Application.Range("N"+2).Text
    let mailer;
    if(push == "是"){
      mailer = SMTP.login({
        host: zdy_host,
        port: zdy_post,
        username: zdy_username,
        password: zdy_pasd,
        secure: true
      });
      mailer.send({
        from: "有道云笔记签到通知<" + zdy_username + ">",
        to: zdy_username,
        subject: "有道云笔记签到通知 - " + data_time,
        text: message
      });
      console.log("已发送邮件至：" + zdy_username);
    }
}

**Comment by imoki** [comment]
感谢代码提交，后续加入
