### ISSUE TITLE
quark换成ql_quark了，直接复制里面内容，复制到quark，提示没登录。

### ISSUE THREAD

**Issue by jp1017** [imoki/sign_script#30]
![image](https://github.com/user-attachments/assets/8f0ba99b-a97b-4d13-9854-579e6133553b)

必须重新拉取，重新生成表格吗？

**Comment by jp1017** [comment]
返回信息：

![image](https://github.com/user-attachments/assets/203fde28-3d3b-45ce-9341-dd5450319925)

**Comment by imoki** [comment]
失效了

**Comment by imoki** [comment]
最新代码已可用，cookie栏填手机抓包的url

**Comment by jp1017** [comment]
不会手机抓啊，电脑网页怎么填写呢？？

**Comment by jp1017** [comment]
不会手机抓啊，电脑网页怎么填写呢？？

**Comment by imoki** [comment]
电脑的不行，只能抓手机app上的url

**Comment by imoki** [comment]
目前测试88vip的此方法无法签，只适用于普通用户

**Comment by imoki** [comment]
抓url的说明已经发在公众号文章了

**Comment by imoki** [comment]
哪再找找，目前很多人都操作成功了，应该没什么问题。主要是url里面含有sign的就八九不离十了

**Comment by imoki** [comment]
sign存活有效期还在检验，目前测试是至少为5天。根据自己情况看是否想跑

**Comment by jp1017** [comment]
找不到sign呢，

**Comment by imoki** [comment]
1.安卓抓包吗，root了吗。无root已测试抓不到
2.是否是会员，是会员无法签到
3.进入夸克app是否点击了夸克网盘，需要点击它

检查这几个，都没问题，那是未知原因了

**Comment by jp1017** [comment]
**成功了！**

华为手机，之前装了AdGuard，今天偶然想到，这家伙过滤请求，按照你的说明，找到了那个请求，复制进去，签到成功！
这也是心想事成吧，因为你本来啥都有，你用心了，就给你显现出来，佛法真不可思议，**南无大乘妙法莲华经**！
感恩！！！
