### ISSUE TITLE
夸克推送需更新

### ISSUE THREAD

**Issue by jp1017** [imoki/sign_script#34]
https://github.com/imoki/sign_script/blob/d4c922554ff9aa7bf1e9cca79363d736b21d4cff/polymerization/ql_quark.js#L84

**Comment by jp1017** [comment]
https://github.com/imoki/sign_script/pull/35

**Comment by imoki** [comment]
十分感谢您的提交！
由于现在已经采用分离式推送了，即通过PUSH.js推送脚本进行统一消息推送，所以签到脚本内的推送已不再使用。
签到脚本内注释掉的推送代码是老的推送方式，如果希望采用老的推送方式就用你的方法，即：取消推送代码的注释。

**Comment by imoki** [comment]
新旧推送方式的区别：
新：
1.签到执行完不发送通知，由PUSH.js统一发生通知。
2.可以将结果整合为一条进行统一通知。
3.通知发送的时间点可以任意设置。
4.以后推送方面的更新仅需更新PUSH.js脚本即可

旧：
1.签到执行完就直接发送通知，
2.推送和签到强耦合，要新增新推送方式用户对每个签到脚本都需要更新，操作较为繁琐

**Comment by jp1017** [comment]
也就是解决了这个问题，https://github.com/imoki/sign_script/issues/25。

**Comment by imoki** [comment]
是的，用到了您提到的后者的方案

**Comment by jp1017** [comment]
https://github.com/imoki/sign_script/commit/02c512f2c4e414e31f2dadf46c2bb28e0481cc5e
