### ISSUE TITLE
我用的WPS Office自动签到，但是运行出错

### ISSUE THREAD

**Issue by hao9ii** [imoki/sign_script#4]
按照公众号内WPS自动签到（轻量版）一文，已在金山在线表格中录入了相关内容（填写上了wps_sid的值），添加好了代码，但是运行代码时并没有像公众号截图标记的那样，而是提示：

11:22:28.254    通知    已开始执行                                                                     <system>
11:22:28.401    信息    {"result":"error","data":"","msg":"need_captcha"}           wps自动签到脚本.js:50:17
11:22:30.434    通知    执行完毕                                                                        <system>

请问是什么原因呢？

**Comment by imoki** [comment]
这个意思是需要验证码。轻量版不稳定，您第一天先手动签到，明天再尝试运行下脚本。有问题可入群交流
