### ISSUE TITLE
金山云文档运行报错。

### ISSUE THREAD

**Issue by nsfw404** [imoki/sign_script#41]
金山云文档运行阿里云盘签到有如下报错：
ReferenceError:Time is not defined
at doTask (aliyun.js:514:21)
at execHandle (aliyun.js:691:11)
at aliyun.js:308:17

**Comment by imoki** [comment]
用的arcript 1.0还是2.0版本？
使用1.0版本运行试试

**Comment by nsfw404** [comment]
请问在那看是1.0还是2.0？

**Comment by imoki** [comment]
脚本类型需要修改为airscript 1.0。目前官方推出2.0 Beta版本了，没对2.0进行适配。

解决方案如下:
方法一：
新建——在线智能文档——智能表格——效率——高级开发——AirScript脚本编辑器——共享脚本——显示为1.0版本

方法二：
添加脚本“+”旁边的“倒三角”符号也能选脚本类型，选择1.0版本

**Comment by imoki** [comment]
编辑器左侧每个脚本名旁边都有版本号。显示Beta就是2.0。
