### ISSUE TITLE
运行日志显示InternalError

### ISSUE THREAD

**Issue by gtjl12** [imoki/sign_script#5]
签到代码手动运行没有问题，定时任务前面也成功过几次，但近两天运行日志会显示InternalError，一行代码都没有执行。
同时有三个定时执行任务，有一个一直可以正常执行，两个都是同样错误日志。
找不到金山客服，借宝地请问各位大神，有没有遇到同样问题？可能是哪些原因？

<img width="225" alt="1" src="https://github.com/imoki/sign_script/assets/13817381/ad717e36-a674-41ae-bcff-04d89071fdf6">

**Comment by SunWuyuan** [comment]
没有创建网络api？每一个要单独创建

**Comment by imoki** [comment]
![image](https://github.com/imoki/sign_script/assets/78804251/4da86a13-3c95-4615-af73-010375e6b2d3)
