### ISSUE TITLE
科研通多账号签到只能一个有效

### ISSUE THREAD

**Issue by zhaoliang0302** [imoki/sign_script#55]
多个账号填在表里，是否签到选的”是“，只有第一个能签到，后面账号的失败

**Comment by imoki** [comment]
公众后后台私发我账号测试

**Comment by imoki** [comment]
可能是以下情况造成的问题：
1.你浏览器登录第二个账号获取ck后，进行了退出操作。不要进行退出，一退出ck就会自动失效。
2.ck抓错了。

**Comment by imoki** [comment]
检查以上问题。
第一类问题可以任选以下一种方式解决。
1.清除浏览器ck后登另一个账户获取ck。
2多用一个浏览器获取另一个账户ck。
3.同一个浏览器，使用无痕模式来获取另一个账户ck。

**Comment by zhaoliang0302** [comment]
感谢，目前我用无痕模式拿ck试一下
