### ISSUE TITLE
使用问题。

### ISSUE THREAD

**Issue by WesleyYeh** [imoki/sign_script#7]
用UPdate.js直接创建定时任务就好吗？还是需要额外操作，用update.js直接进行运行，只看到新建的表格，没有进行推送。

**Comment by imoki** [comment]
update脚本只创建表格。定时任务需要自己手动添加。

**Comment by imoki** [comment]
详细教程可以看“默库”公众号的文章

**Comment by WesleyYeh** [comment]
谢谢 搞明白了
