### ISSUE TITLE
A2单元格失败

### ISSUE THREAD

**Issue by YoYoYoKing283** [imoki/sign_script#9]
老哥，显示A2单元格失败是什么原因呢？

**Comment by imoki** [comment]
哪个脚本。
检查以下错误
1.是否有添加网络API，要添加
2.ck是否填写正确，有的脚本是填token之类的。
3.ck前后是否有多余的内容，如换行、双引号等。需要删掉

**Comment by YoYoYoKing283** [comment]
ntsd2.4百度云链接:https://pan.baidu.com/s/1CVy_kAaXJcdn1tViBygonA 密码:2vm2

**Comment by YoYoYoKing283** [comment]
老哥是吾爱破解脚本，需要要添加API吗？

**Comment by imoki** [comment]
细节部分你看下“默库”公众号文章

**Comment by imoki** [comment]
要。
其中cookie内至少要包含 以下两个键值对：htVC_2132_saltkey=xxxxxxxx; htVC_2132_auth=xxxxxxxx;

**Comment by YoYoYoKing283** [comment]
好的谢谢老哥
